name: Hypertune

on:
  push:
    branches:
    - master
    - testing
jobs:
  library:
    #    if: github.event.comment.body == 'test core'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
    steps:
    - run: |
        pip install -U hypertune
  tests:
#    if: github.event.comment.body == 'test core'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        which python
        python -m pip install --upgrade pip
    - name: Install test dependencies
      run: pip install -r hypertune/requirements/test.txt
    - name: Install master dependencies
      run: pip install -r hypertune/requirements/master.txt
    - name: Install dev libraries
      run: export USE_LOCAL_PACKAGES="true" && pip install --upgrade --editable "hypertune[dev]"
    - name: Test with pytest
      run: |
        cd hypertune
        pytest -vv
